# Generated by Django 2.0.7 on 2018-08-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoConfigInfos',
            fields=[
                ('server_num', models.TextField(blank=True, null=True)),
                ('board', models.TextField(blank=True, null=True)),
                ('memory_bank', models.TextField(blank=True, null=True)),
                ('hard_disk', models.TextField(blank=True, null=True)),
                ('raid', models.TextField(blank=True, null=True)),
                ('vga', models.TextField(blank=True, null=True)),
                ('gpu', models.TextField(blank=True, null=True)),
                ('hba', models.TextField(blank=True, null=True)),
                ('net_card', models.TextField(blank=True, null=True)),
                ('fc_card', models.TextField(blank=True, null=True)),
                ('inspect_time', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('ip_info', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.TextField(blank=True, null=True)),
                ('checkstate', models.IntegerField(blank=True, null=True)),
                ('cpu', models.TextField(blank=True, null=True)),
                ('aging_data', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
